[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
auto_detect_solc = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
sepoliaTestnet = { key = "${ETHERSCAN_API_KEY}", url = "${SEPOLIA_VERIFIER_URL}", chain = 11155111 }
sophonTestnet = { key = "this-is-not-a-real-key", url = "https://api-explorer-verify.testnet.sophon.xyz/contract_verification", chain = 531050104 }

[rpc_endpoints]
sepoliaTestnet = "${SEPOLIA_RPC_URL}"
sophonTestnet = "${SOPHON_RPC_URL}"